/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_firelord_Test */

#ifndef _Included_com_firelord_Test
#define _Included_com_firelord_Test
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_firelord_Test
 * Method:    start0
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_firelord_Test_start0
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
